### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by mkaomwakuni** [mkaomwakuni/Weaver-News-App#19]
![Screenshot_20240207-150725_Weaver 1 -portrait](https://github.com/mkaomwakuni/Weaver-News-App/assets/61048381/d513189a-8b36-4029-b276-4cd1e5623d75)
![Screenshot_20240207-144024_Weaver-portrait](https://github.com/mkaomwakuni/Weaver-News-App/assets/61048381/0d31bde3-ab18-4607-9ea4-332a9218ac8d)
![Screenshot_20240207-144047_Weaver-portrait](https://github.com/mkaomwakuni/Weaver-News-App/assets/61048381/c021f84b-c52f-4ad6-b659-986b96694e97)

**Comment by mkaomwakuni** [comment]
![Uploading WhatsApp Image 2024-02-06 at 7-portrait.png…]()

**Comment by mkaomwakuni** [comment]
![WhatsApp Image 2024-02-06 at 7-portrait](https://github.com/mkaomwakuni/Weaver-News-App/assets/61048381/3d35ef50-c51d-4d9f-9565-74a51ede4000)

**Comment by mkaomwakuni** [comment]
![Screenshot_20240718-191128_Weaver](https://github.com/user-attachments/assets/93dc0152-4ea7-4736-ab60-4e1a41fac946)
![Screenshot_20240718-191110_Weaver](https://github.com/user-attachments/assets/186a7672-1c39-4e71-88e0-bed24b35907d)
![Screenshot_20240718-191018_Weaver](https://github.com/user-attachments/assets/fd2dffdf-c7f0-4631-84b3-4f3a6d303ff8)

**Comment by mkaomwakuni** [comment]
![1](https://github.com/user-attachments/assets/16f50413-8a02-4eb3-87f3-c255a3cee1a4)
![2](https://github.com/user-attachments/assets/3a136566-0a95-42a2-a157-c8d6920fc976)
![3](https://github.com/user-attachments/assets/5ae68799-0641-4d57-9eb0-f4c9159abbbc)
![4](https://github.com/user-attachments/assets/2736ce50-b140-4a4d-8f38-99303c5ab05f)
![5](https://github.com/user-attachments/assets/33d54be5-c232-4b09-946b-4e5ac69566a8)

**Comment by mkaomwakuni** [comment]
![Screenshot_20240718-215155_Weaver 1 -portrait](https://github.com/user-attachments/assets/3a7e9ba6-599c-4c95-a434-747d5372122b)
![Screenshot_20240718-215829_Weaver 1 -portrait](https://github.com/user-attachments/assets/06117615-d0a4-429e-8c74-0073037b3792)

**Comment by mkaomwakuni** [comment]
![1](https://github.com/user-attachments/assets/95b413b8-9370-40fe-8283-e3b46b5295fc)
![2](https://github.com/user-attachments/assets/27657eda-a6f8-40ac-a7f0-08f6bad46680)
![3](https://github.com/user-attachments/assets/8f9434b3-bd88-4778-9712-d59214cd4010)
![4](https://github.com/user-attachments/assets/cbeded64-be2c-4eb1-b7b3-39cfd75e6b84)
![5](https://github.com/user-attachments/assets/58e93298-0097-4951-b9f7-de0e7d012101)
![Screenshot_20240718-215155_Weaver 1 -portrait](https://github.com/user-attachments/assets/beaebca9-bf7a-4429-a58c-1600edac5f77)

**Comment by mkaomwakuni** [comment]
![bk](https://github.com/user-attachments/assets/c2e9d3e2-bb65-4e0d-bf5a-58edca0fc56f)
![bt](https://github.com/user-attachments/assets/b5344d42-5034-4ee2-bffa-dc73d778a9d5)

**Comment by imkao0** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/23bc32a7-a01a-4273-9aef-a4ed8ebc845b" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e50b53b5-e9b1-44a0-a55d-093f58959d5f" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/5e719d19-e5ed-4c70-94ea-cc6e3079ddba" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/b3f0d5eb-9a67-4645-bc82-8c4ee08ad727" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/fdc8651a-a6b7-4d12-b626-84cc5b0f0f79" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/a7347bdb-d638-4d3b-a183-b78046440b4b" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/4af125e9-1964-4fbd-9100-8fb3cbd24b58" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/2e90d082-1a16-4efa-9e89-9febeb18588a" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/f50a09ea-29a9-4bac-ab62-51ba031e57c3" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/512f82b4-6ca2-4fe6-8cf4-1593fac4071c" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/b9e993d9-fefa-4e42-99ec-427dd2500056" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/c4a91757-b299-45b3-8852-75233844b779" />
